### ISSUE TITLE
NPE when invalid data is provided

### ISSUE THREAD

**Issue by martin-g** [isisaddons-legacy/isis-wicket-wickedcharts#2]
With the current Java Math demo data in the KitchenSink application trying to show a `summarychart` leads to the following exception:

```
Caused by: java.lang.NullPointerException
    at java.math.BigDecimal.compareTo(BigDecimal.java:2554)
    at java.math.BigDecimal.min(BigDecimal.java:2665)
    at org.isisaddons.wicket.wickedcharts.cpt.ui.summarychart.CollectionContentsAsSummaryChart.minOf(CollectionContentsAsSummaryChart.java:163)
    at org.isisaddons.wicket.wickedcharts.cpt.ui.summarychart.CollectionContentsAsSummaryChart.createChartValue(CollectionContentsAsSummaryChart.java:119)
    at org.isisaddons.wicket.wickedcharts.cpt.ui.summarychart.CollectionContentsAsSummaryChart.buildGui(CollectionContentsAsSummaryChart.java:101)
    at org.isisaddons.wicket.wickedcharts.cpt.ui.summarychart.CollectionContentsAsSummaryChart.onModelChanged(CollectionContentsAsSummaryChart.java:168)
```

**Comment by danhaywood** [comment]
moved to https://github.com/incodehq/incode-platform/issues/29
